### ISSUE TITLE
Failed to load Dependency api-ms-win-crt-runtime-l1-1-0.dll

### ISSUE THREAD

**Issue by cynocoder** [DarthTon/Blackbone#61] opened 2016-02-11 20:26 UTC
[screenshot of console output](http://grabilla.com/0620b-66783177-e857-4d92-a324-ec30f9550efb.png)

it works fine without the ManualImports flag

win8.1 x64. Target module linked with /MD & compiled with VS 2015

**Comment by DarthTon** [comment] 2016-02-17 11:12
Duplicate of #58

**Closed by DarthTon** 2016-02-17 11:12 UTC
