### ISSUE TITLE
Manual map: call of entry point hangs target

### ISSUE THREAD

**Issue by residentkms** [DarthTon/Blackbone#106] opened 2016-11-02 06:32 UTC
Hello, im using user-mode manual map to inject dll into process.
Its working perfectly, but in ~30% cases target process crashes (with any flags) when calling entry point. And i cant understand why it occurs and how i can debug it. 
upd.  
With Xenos the same.
I think that wrong build settings for dll....

**Comment by staticinvocation** [comment] 2016-11-04 05:05
I can't reproduce this.

Could you please maybe upload the DLL, or perhaps a crash dump?

**Comment by residentkms** [comment] 2016-11-04 13:00
Thank you for response.
Dump and dll here: https://www.dropbox.com/sh/kf3gmp5cok6vfhs/AABkEVF7Yu7HIw2IKNTpsPgWa?dl=0
Sorry for mistake, it falls at "Performing security cookie"
Console output:
BlackBone: ManualMap: Mapping image 'F:\Cloud\...\out\Debug\img.dll' with flags 0x1002
BlackBone: ManualMap: Loading new image 'F:\Cloud\...\out\Debug\img.dll'
BlackBone: ManualMap: Image base allocated at 0x23670000
BlackBone: ManualMap: Performing image copy
BlackBone: ManualMap: Relocating image 'F:\Cloud\...\out\Debug\img.dll'
BlackBone: ManualMap: Loading new dependency 'msvcp140d.dll'
BlackBone: ManualMap: Dependency path resolved to 'C:\Windows\system32\msvcp140d.dll'
BlackBone: ManualMap: Performing security cookie initializtion for image 'img.dll'

**Comment by staticinvocation** [comment] 2016-11-04 14:51
Duplicate of #101?

**Comment by residentkms** [comment] 2016-11-04 15:04
I dont know, but suggested there method not help to me.

**Comment by residentkms** [comment] 2016-11-06 11:35
So, i figured crash happens when code from AddStaticTLSEntry()/RunModuleInitializers()/etc runs on worker thread. With any/new thread it works nicely. But why others can map without any modifications.....

**Closed** 2016-11-06 11:35 UTC
